update README notes
andreienea1990/mobileAutomation_appium pull request #17
Opened 2023-08-21 08:55 UTC by Aransadorien09

Update README notes

2023-08-21 09:08 UTC, andreienea1990 commented on README.md
> +11. Create a new test suite:
Nu avem nevoie de astea, avem nevoie de pasii pe care trebuie sa-i faca cineva sa poata rula curent project :) Nu cum se face de la inceput , ci cum as putea eu sa-mi setez : Windows / MacOs sa-mi poata merge solutia de automation + alte detalii gen de proiect - gen - aici se scriu testele , aici se pun feature si etc.

2023-08-21 11:08 UTC, apostolroxana4 requested changes

2023-08-21 11:08 UTC, apostolroxana4 commented on README.md
> +"pip install robotframework". Check if the installation was successful by executing command "robot --version"
Cred ca ai putea sa costmetizezi putin continul, sa pui bold sau italic la ce este scris in ghilimele

2023-08-21 11:08 UTC, apostolroxana4 commented on README.md
> +5. Start appium inspector and set appium server with data specific to your specific desired capabilities
Poti sa adaugi si partea de appium doctor

2023-09-12 06:25 UTC, andreienea1990 commented on demoapp/ApiDemos-debug.apk
De ce ai adaugat aplicatia ?

2023-10-11 06:56 UTC, closed without merging